### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by HwDhyeon**

### CODE REVIEW

**Comment by HwDhyeon** [comment]
This PR is highly illogical..

**Comment by HwDhyeon** [comment]
This PR is highly illogical..

**Comment by HwDhyeon** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
This PR is highly illogical..

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
This PR is highly illogical..

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
POST Message with FAILURE

**Comment by mobigen-irisdev** [comment]
This PR is highly illogical..

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
POST Message with FAILURE

**Comment by mobigen-irisdev** [comment]
This PR is highly illogical..

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
POST Message with FAILURE

**Comment by mobigen-irisdev** [comment]
Test results -> success: 103, failure: 17, skipped: 3

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
./main.py:3:1: E302 expected 2 blank lines, found 0
./main.py:6:1: E302 expected 2 blank lines, found 1
./main.py:9:1: E302 expected 2 blank lines, found 1
./main.py:10:9: W292 no newline at end of file

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
|file|line|message|
|:---:|:---:|:---:|
|./main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|./main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|10line 9pos|W292 no newline at end of file|
|./main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|./main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|10line 9pos|W292 no newline at end of file|

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Comment by mobigen-irisdev** [comment]
POST Message with FAILURE

**Comment by mobigen-irisdev** [comment]
POST Message with FAILURE

**Comment by mobigen-irisdev** [comment]
## Flake8 result
Link -> [pr_comment_test » PR-1 #14](http://cicd.mobigen.com/job/pr_comment_test/job/PR-1/14/)
|file|line|message|
|:---:|:---:|:---:|
|./main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|./main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|10line 9pos|W292 no newline at end of file|
|./main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|./main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|./main.py|10line 9pos|W292 no newline at end of file|
|main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|main.py|10line 9pos|W292 no newline at end of file|
|main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|main.py|10line 9pos|W292 no newline at end of file|
|main.py|3line 1pos|E302 expected 2 blank lines, found 0|
|main.py|6line 1pos|E302 expected 2 blank lines, found 1|
|main.py|9line 1pos|E302 expected 2 blank lines, found 1|
|main.py|10line 9pos|W292 no newline at end of file|

**Comment by mobigen-irisdev** [comment]
POST Message with SUCCESS

**Pull request closed without merging**
